version: '3.8'
services:

  smartroom_airquality_api_students:
    container_name: smartroom_airquality_api_students
    build:
      context: .
      dockerfile: ./SmartRoom_AirQuality/Dockerfile
    networks:
      - db_network
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    ports:
      - 8002:8002
      - 1883:1883
    depends_on:
      - timeScaleDatabaseSRAQ
    volumes:
      - ./SmartRoom_AirQuality/api/:/app/
      - ./SmartRoom_AirQuality/devices.json:/app/devices.json
    environment:
      - TZ=Europe/Paris

  subscriber:
    container_name: smartroom_mqtt_subscriber
    build:
      context: .
      dockerfile: ./SmartRoom_AirQuality/Dockerfile_subscriber
    networks:
      - db_network
    command: python subscriber.py

    depends_on:
      - smartroom_airquality_api_students
    volumes:
      - ./SmartRoom_AirQuality/devices.json:/app/devices.json

  grafana_students:
    container_name: grafana_students
    image: grafana/grafana:9.0.6
    ports:
      - 3001:3000
    networks:
      - db_network

  timeScaleDatabaseSRAQ:
    container_name: timeScaleDatabaseSRAQ
    image: timescale/timescaledb-ha:pg14-latest
    restart: always
    networks:
      - db_network
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
      - ./Database_Schema.sql:/docker-entrypoint-initdb.d/Database_Schema.sql
    environment:
      - PGDATA=/var/lib/postgresql/data/timescale/
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cdlmint
      - POSTGRES_DB=cdl-mint

  pgadmin_students:
    container_name: pgadmin_students
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - db_network
    ports:
      - 5055:80
    depends_on:
      - timeScaleDatabaseSRAQ

volumes:
  postgres_data:
  devices.json:
networks:
  db_network:
    driver: bridge
